Apple rust toolchain building `lzma` from source
I have been running `build_rust.py` locally on my computer, and it has
run into issues with the system installed liblzma, which is brought in
transiently by all sorts of homebrew packages. This was causing failures
like this one:

```
warning: linker stderr: ld64.lld: /opt/homebrew/Cellar/xz/5.8.3/lib/liblzma.dylib has version 26.0.0, which is newer than target minimum of 11.0.0
  |
  = note: `#[warn(linker_messages)]` on by default

error: `bootstrap` (bin "bootstrap") generated 1 warning
error: warnings are denied by `build.warnings` configuration
```

This CL enables this env for `darwin` systems, the same way it is
already enabled for `debian_sysroot`.

Bug: 518635459
Change-Id: I96c6349da9e04146c89ff50f7fd480b15a6f2234
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7912649
Reviewed-by: Devon Loehr <dloehr@google.com>
Commit-Queue: Łukasz Anforowicz <lukasza@chromium.org>
Reviewed-by: Sylvain Defresne <sdefresne@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1644641}
NOKEYCHECK=True
GitOrigin-RevId: c3c82158ac2d8300d9a4df84b8fe862201adeb2e