Pick up a patch to escape spaces in bindgen's depfile outputs
Windows paths have spaces in them and they need to be escaped or
ninja can't track dependencies correctly.

This rolls bindgen to HEAD (roughly 0.65.1) at the same time, which
has a couple visible changes:

The size_t-is-usize argument has been inverted and replaced, so
remove our use of it from run_bindgen.py.
```
error: unexpected argument '--size_t-is-usize' found
  note: argument '--no-size_t-is-usize' exists
```

The `clap` feature has also been removed, so remove our use of it
when building bindgen.

Bug: 1271215
Change-Id: Ic3b745642da415b28bdeee4ff0398d701214118f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4420089
Commit-Queue: danakj <danakj@chromium.org>
Reviewed-by: Collin Baker <collinbaker@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1130620}
NOKEYCHECK=True
GitOrigin-RevId: 80493f1787a837794c5557ec29390c1573a03930